version: "2"
services:
  web:
    build: .
    ports:
      - 9060:80
    environment:
      HOST: ${MYSQL_HOST}
      PORT: ${MYSQL_PORT}
      USER: ${MYSQL_USER}
      PW: ${MYSQL_PW}
      DB: ${MYSQL_DB}
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: ${MYSQL_DB}